pipeline {
    agent any
    
    stages {
        stage('Clone Repository') {
            steps {
                // Clone the repository
                git 'https://github.com/emzm/jenkins_pipelines_all_apps.git'
            }
        }
        
        stage('Build') {
            steps {
                // Navigate to the directory containing pom.xml
                dir('springboot-app') {
                    // Run Maven build
                    sh '/opt/maven/bin/mvn clean install'
                }
            }
        }
        
        stage('Test') {
            steps {
                // Run Maven tests
                dir('springboot-app') {
                    sh '/opt/maven/bin/mvn test'
                }
            }
        }
        
        stage('Publishing Junit Tests report') {
            steps {
                junit 'springboot-app/target/surefire-reports/*.xml'
            }   
        }
        
        stage('Publishing Code Coverage') {
            steps {
                jacoco()
            }   
        }
        
        stage('Image push to local Docker registry') {
            steps {
                sh 'docker version'
                sh 'docker build -t dockerregistry.com/springbootjacoco:0.0.1 -f Dockerfile .'
                withDockerRegistry(credentialsId: 'docker-cred', url: 'https://dockerregistry.com/v2/') {
                    sh 'docker push dockerregistry.com/springbootjacoco:0.0.1'
                }
            }
        }
    }
}
